# Generated by Django 3.2.9 on 2022-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la tarea')),
                ('tituloTarea', models.CharField(max_length=15, verbose_name='Titulo de la tarea')),
                ('textoTarea', models.CharField(max_length=80, verbose_name='Texto de la tarea')),
                ('estadoTarea', models.BooleanField(default=False, verbose_name='Tarea completa o no')),
                ('fechaRegistro', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion de la tarea')),
                ('fechaTermino', models.DateField(verbose_name='Fecha de termino de la tarea')),
                ('ultimaModificacion', models.DateField(auto_now=True, verbose_name='Fecha del ultimo cambio')),
            ],
        ),
    ]
