# Generated by Django 3.2.9 on 2022-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_to_do', '0002_alter_tarea_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaTermino',
            field=models.DateTimeField(verbose_name='Fecha de termino de la tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='ultimaModificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha del ultimo cambio'),
        ),
    ]
