# Generated by Django 3.2.9 on 2022-01-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_to_do', '0005_remove_tarea_ultimamodificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='ultimaModificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha del ultimo cambio'),
        ),
    ]
