# Generated by Django 3.2.9 on 2022-02-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_to_do', '0007_auto_20220201_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='textoTarea',
            field=models.CharField(max_length=25, verbose_name='Texto de la tarea'),
        ),
    ]
